server:
  port: 8080
  contextPath: /LeadManagement
  display-name: LeadManagement
  error.include-stacktrace: never
  error.path: /error
  error.whitelabel.enabled: true
  server-header: 'No reponse from server probably an Error occurred on server'
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  
---


spring:
    profiles: serveremail
email: 
     host: smtpout.secureserver.net
     port: 3535
     username: leadmanagement@infocusonline.net
     cc: leadmanagement@infocusonline.net
     password: pfc20!7
     properties: 
        mail.smtp.auth: true 
        mail.smtp.starttls.enable: true
        mail.transport.protocol: smtp
        mail.debug: false
--- 
 logging:
    level:
        com.pfchoice.springboot.SpringBootCRUDApp: WARN
  #       org.ehcache.sample: WARN
   #      io.github.jhipster: WARN  
 #   file: C:/softwares/mavenproject/LeadManagement/logger.log
 
---      

management.security.enabled: false 

spring:
  profiles:
    active: "server,serveremail"
  main:
    banner-mode: "off"
 
---   
                      
spring:
  profiles: local,default
  devtools:
      restart:
          enabled: true
      livereload:
          enabled: true # we use gulp + BrowserSync for livereload
  jpa:
    open-in-view: false
    properties:
       hibernate:
         jdbc.time_zone: America/New_York
         cache.use_second_level_cache: true
         cache.use_query_cache: false
         generate_statistics: false
         show_sql: false
         format_sql: false
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         enable_lazy_load_no_trans: true
         default_batch_fetch_size: 25
         hbm2ddl.method: none
  datasource:
      url: jdbc:mysql://localhost:3306/lead_management?tinyInt1isBit=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true&useLegacyDatetimeCode=false
      username: root
      password: test123
      driverClassName: com.mysql.jdbc.Driver
      defaultSchema:
      hikari:
          connectionTimeout: 60000
          idleTimeout: 30000
          maxLifeTime: 3600000
          maxPoolSize: 30
          minimumIdle: 3
          poolName: "LEAD_DB_POOL"
          isAutoCommit: false         
envProperties:
      coordinatorEmail: skumar@pfchoice.com
      coordinatorName: Sarath     

---
                      
spring:
  profiles: server
  jpa:
    open-in-view: false
    properties:
       hibernate:
         jdbc.time_zone: America/New_York
         cache.use_second_level_cache: true
         cache.use_query_cache: false
         generate_statistics: false
         show_sql: false
         format_sql: false
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         enable_lazy_load_no_trans: true
         default_batch_fetch_size: 25
         hbm2ddl.method: none
  datasource:
    url: jdbc:mysql://pras-aws-prod.cp2ok1lxfh49.us-east-1.rds.amazonaws.com:3306/lead_management?tinyInt1isBit=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true&useLegacyDatetimeCode=false
    username: pfcdbadmin
    password: pfcdb20!7
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    hikari:
        connectionTimeout: 60000
        idleTimeout: 30000
        maxLifeTime: 3600000
        maxPoolSize: 30
        minimumIdle: 3
        poolName: "LEAD_DB_POOL"
        isAutoCommit: false
envProperties: 
      coordinatorEmail: dsoto@pfchoice.com
      coordinatorName: Dynahly Soto                  
 
 
---   
spring:
 http:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB