server:
  port: 8080
  contextPath: /LeadManagement
---

email: 
     host: smtp.office365.com
     port: 587
     username: skumar@pfchoice.com
     cc: skumar@pfchoice.com
     password: Khammam12g
     properties: 
        mail.smtp.auth: true 
        mail.smtp.starttls.enable: true
        mail.transport.protocol: smtp
        mail.debug: false
  
spring:
  profiles: local,default
datasource:
  leadManagement:
    url: jdbc:mysql://localhost:3306/lead_management?tinyInt1isBit=false
    username: root
    password: test123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: validate
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect


 
