server:
  port: 8080
  contextPath: /LeadManagement
---

email: 
     host: smtp.office365.com
     port: 587
     username: skumar@pfchoice.com
     cc: skumar@pfchoice.com
     password: Florida6
     properties: 
        mail.smtp.auth: true 
        mail.smtp.starttls.enable: true
        mail.transport.protocol: smtp
        mail.debug: false
---
spring:
    profiles: newyork
    jpa:
        properties:
            hibernate:
                jdbc:
                    time_zone: America/Indiana/Indianapolis
                    
---

spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"
 
---   
                      
spring:
  profiles: local,default
datasource:
  leadManagement:
    url: jdbc:mysql://localhost:3306/lead_management?tinyInt1isBit=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: test123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: none
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect

---
                      
spring:
  profiles: server
datasource:
  leadManagement:
    url: jdbc:mysql://pras-aws-prod.cp2ok1lxfh49.us-east-1.rds.amazonaws.com:3306/lead_management?tinyInt1isBit=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: pfcdbadmin
    password: pfcdb20!7
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: none
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect
 
