server:
  port: 8080
  contextPath: /LeadManagement
---

email: 
     host: smtp.office365.com
     port: 587
     username: skumar@pfchoice.com
     cc: skumar@pfchoice.com
     password: Florida6
     properties: 
        mail.smtp.auth: true 
        mail.smtp.starttls.enable: true
        mail.transport.protocol: smtp
        mail.debug: false
  
spring:
  profiles: local,default
datasource:
  leadManagement:
    url: jdbc:mysql://pras-aws-prod.cp2ok1lxfh49.us-east-1.rds.amazonaws.com:3306/lead_management?tinyInt1isBit=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: pfcdbadmin
    password: pfcdb20!7
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect


 
