server:
  port: 8080
  contextPath: /LeadManagement
---
spring:
  profiles: local,default
datasource:
  leadManagement:
    url: jdbc:mysql://localhost:3306/lead_management?tinyInt1isBit=false
    username: root
    password: test123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect